### PR TITLE
Fix highlighting for strings nested in urls

### LINKED ISSUE #16: Quoted strings are not highlighted in url()
In Sublime Text, I noticed that when I do something like `background: url("image.png");` the quoted string is not highlighted. Looks like the definition for `url()` (lines 107-114) are overriding that of quotes.

Does `url()` need special treatment? For me at least it doesn't show up as highlighted at all anyway. You could remove that entire section and just have `url` as a keyword in the `support.constant.property-value.sass` section.

### PR DESCRIPTION
**Pull request by guerrero**
This fix #16

Before changes:
captura de pantalla 2015-06-07 a las 4 34 55

After changes:
captura de pantalla 2015-06-07 a las 4 33 57

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Ohai. Any chance we could get this merged @nathos?

**Comment by nathos** [comment]
@HugoGiraudel any feedback/testing on this for both ST2 & ST3? The changes look good to me, but I'd love to have another set of :eyes: on it.

**Comment by HugoGiraudel** [comment]
Hey @nathos, I'm glad your still maintaining this. I'll give it a try tomorrow and tell you what. :)

**Comment by nathos** [comment]
@HugoGiraudel thanks so much. Please let me know what you find. I've switched much of my day-to-day editing to Atom, but I'd like to get enhancements/fixes to the Sublime package released in a responsible way :)

**Comment by HugoGiraudel** [comment]
One thing you could would be to say it's for both ST2 and 3 for starters. ;)

**Comment by nathos** [comment]
@HugoGiraudel done :smile:: https://github.com/nathos/sass-textmate-bundle/commit/4593ed591063ead49bef81c26238cde48afda4b8

**Comment by HugoGiraudel** [comment]
Ah, nice. :)

**Comment by HugoGiraudel** [comment]
@nathos Unfortunately I don't know how to test a local package... :(

**Comment by nathos** [comment]
@HugoGiraudel It's probably easiest using GitHub for Mac/Windows. You'll need to:

1. Uninstall the current version of the package if you've installed it with Package Control
2. In Sublime Text go to: `Preferences > Browse Packages...` and make note of the directory path.
3. Click the "Check out this branch in GitHub for Mac (or Windows)" button like the one pictured below: screen shot 2015-06-08 at 4 55 00 pm
4. In the dialog box that appears, clone the repo to the path in step 2.
5. Test away!

**Comment by HugoGiraudel** [comment]
@nathos 

* Single-quotes strings are now properly highlighted
* `@error` is now properly recognized

@guerrero 

I can't seem to highlight a string inside `url(..)`. Any idea?

**Comment by guerrero** [comment]
Sorry @HugoGiraudel, the branch created to fix strings nested into url strings wasn't merged. Try it now, it should work.

**Comment by HugoGiraudel** [comment]
All good. @nathos LGTM! :+1:

**Pull request merged**
